### ISSUE TITLE
Quartz missing from python3

### ISSUE THREAD

**Issue by bandrel** [glitchassassin/keyboard#1]
I'm unfamiliar with Quartz, but based on my readings it looks like it is provided by Apple for the built in python version of 2.7.  Since keyboard is supposed to be python 2 or 3 compatible I thought I should raise the issue.
```
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Quartz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Quartz'
```

**Comment by glitchassassin** [comment]
This requires the PyObjC module:

    pip install pyobjc

**Comment by glitchassassin** [comment]
I'll update the requirements file. Thanks!

**Comment by glitchassassin** [comment]
I've updated the fork with a couple other bugfixes as well. Let me know if you see any issues with your testing - if not, I'll create a pull request.

Thanks!

**Comment by bandrel** [comment]
setup.py is missing  
```import sys```
but other than that so good so far.

**Comment by glitchassassin** [comment]
Fixed.
